const ReduxActionTypes = {
  INIT_APP: "INIT_APP",
  APP_INITIALIZED: "APP_INITIALIZED",

  POLLING_INIT: "POLLING_INIT",
  REMOVE_POLLING_TASK: "REMOVE_POLLING_TASK",
  ADD_POLLING_TASK: "ADD_POLLING_TASK",
  POLLING_STOP: "POLLING_STOP",
};

export default ReduxActionTypes;
